routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('tes','HomeController@query');
Auth::routes();

Route::group(['prefix' => 'siswa'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/raport','HomeController@indexRaport')->name('index.raport.siswa');
    Route::get('/cetak-raport/{id}','HomeController@printRaport')->name('print.raport.siswa');
    Route::get('/akun/{id}','SiswaController@akun')->name('akun.siswa.show');
    Route::post('/akun/ubah/{id}','SiswaController@updateAkun')->name('akun.siswa.update');
});

Route::get('raport', 'RaportController@cetak');
Route::get('/','GuruController@index')->middleware('guru');

Route::group(['middleware'=>'guru', 'prefix' => 'admin'], function () {
    Route::get('/','GuruController@index');
    Route::resource('guru', 'GuruController');
    Route::resource('siswa', 'SiswaController');
    Route::resource('jurusan', 'JurusanController');
    Route::resource('matapelajaran', 'MatapelajaranController');
    Route::resource('kelas', 'KelasController');
    Route::resource('nilai-akademik', 'NilaiakademikController')->except('create');
    Route::resource('raport', 'RaportController')->except('create');
    Route::resource('ekskul', 'EkskulController');
    Route::resource('pkl', 'PKLController');
    Route::get('/akun/{id}','GuruController@akun')->name('akun.guru.show');
    Route::post('/akun/ubah/{id}','GuruController@updateAkun')->name('akun.guru.update');

    Route::get('raport/create/{id}', 'RaportController@create')->name('raport.create');
    Route::get('raport/kelas/{kelas}/nilai-akademik', 'RaportController@indexNilai')->name('raport.index.nilai');
    Route::get('raport/kelas/{kelas}/nilai-akademik/tambah', 'RaportController@createNilai')->name('raport.create.nilai');
    Route::get('raport/kelas/{kelas}/nilai-akademik/buat', 'RaportController@generateNilai')->name('raport.generate.nilai');
    Route::post('raport/kelas/{id}/nilai-akademik/cek', 'RaportController@checkNilai')->name('raport.check.nilai');
    Route::post('raport/kelas/{id}/nilai-akademik/generate', 'RaportController@generateNilai')->name('raport.generate.nilai');
    Route::post('raport/kelas/{kelas}/nilai-akademik/detail', 'RaportController@detailNilai')->name('raport.detail.nilai');

    Route::get('nilai-akademik/siswa/{id}', 'NilaiakademikController@indexNilai')->name('cari.nilai.siswa');
    Route::get('nilai-akademik/kelas/{kelas}/mapel/', 'NilaiakademikController@indexMapel')->name('nilai.mapel.index');
    Route::get('nilai-akademik/kelas/{kelas}/mapel/{mapel}', 'NilaiakademikController@indexNilai')->name('nilai.index2');
    Route::post('nilai-akademik/kelas/{kelas}/mapel/{mapel}/tambah', 'NilaiakademikController@create')->name('nilai-akademik.create');
    Route::get('raport/siswa/{id}', 'RaportController@indexNilai')->name('cari.raport.siswa');
    Route::get('nilai-akademik/create/{id}', 'NilaiakademikController@create')->name('nilai.siswa.create');
    Route::post('nilai-akademik/find-semester', 'NilaiakademikController@orderBySemester')->name('nilai.siswa.semester');
    Route::post('nilai-akademik/find-semester-edit/{id}', 'NilaiakademikController@orderBySemesterEdit')->name('nilai.siswa.semester2');

    Route::get('kepsek','HomeController@kepsekForm')->name('kepsek.show');
    Route::post('kepsek/update','HomeController@kepsekUpdate')->name('kepsek.update');
});

app/Kelas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    protected $fillable = ['nama','jurusan_id','guru_id','nomor'];

    public function guru()
    {
        return $this->belongsTo('App\Guru','guru_id');
    }

    public function jurusan()
    {
        return $this->belongsTo('App\Jurusan','jurusan_id');
    }

    public function siswa()
    {
        return $this->hasOne('App\Siswa');
    }
}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use App\Kelas;
use App\Guru;
use App\Jurusan;
use Auth;
use Illuminate\Http\Request;

class KelasController extends Controller
{
    /**
     * controller ini berfungsi untuk mengelola
     * data kelas yang termasuk tambah,ubah
     * dan hapus
     */
    public function index()
    {
        if(request()->ajax()){
            $data = Kelas::with('guru')->with('jurusan')->get();
            return datatables()->of($data)
                    ->addIndexColumn()
                    ->addColumn('jurusan', function($data){
                        return empty($data->jurusan->nama) ? "Belum Diatur" : $data->jurusan->nama;
                    })
                    ->addColumn('walikelas', function($data){
                        return empty($data->guru->nama) ? "Belum Diatur" : $data->guru->nama;
                    })
                    ->addColumn('action', function($data){
                        $button = '<div class="btn-group" role="group" aria-label="Basic example">
                        <a href="'.route("kelas.edit",$data->id).'"class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                        <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$data->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deleteProduct"><i
                        class="fa fa-trash"></i></a></div>';
                        return $button;
                    })
                    ->rawColumns(['action','walikelas','jurusan'])
                    ->make(true);
        }

        return view('admin.kelas.index');
    }

    /**
     * proses mengarahkan ke halaman
     * formulir tambah data kelas
     *
     */
    public function create()
    {
        $guru = Guru::all();
        $jurusan = Jurusan::all();
        return view('admin.kelas.form',compact('guru','jurusan'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $kelas = Kelas::create($request->all());
        return redirect()->route('kelas.index')->with('success','Berhasil menambah data');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kelas = Kelas::findOrFail($id);
        return view('admin.kelas.show',compact('kelas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kelas = Kelas::findOrFail($id);
        $guru = Guru::all();
        $jurusan = Jurusan::all();
        return view('admin.kelas.form',compact('kelas','guru','jurusan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $kelas = Kelas::findOrFail($id);
        $kelas->update($request->all());
        return redirect()->route('kelas.index')->with('success','Berhasil merubah data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (request()->ajax()) {
            $kelas = Kelas::find($id);
            $kelas->delete();
            return response()->json(['success'=>'berhasil menghapus data']);
        }
    }
}

resources/views/admin/kelas/form.blade.php
@extends('admin.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Kelas </li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">Kelas </h1>
        </header>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                <li>Proses Gagal!!!</li>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                        @isset ($kelas)
                        <div class="card-header d-flex align-items-center">
                            <h4>Ubah Data Kelas</h4>
                        </div>
                        <div class="card-body">
                        <form action="{{route('kelas.update',$kelas->id)}}" method="POST">
                            @method('PUT')
                            @else
                            <div class="card-header d-flex align-items-center">
                                <h4>Tambah Data Kelas</h4>
                            </div>
                            <div class="card-body">
                            <form action="{{route('kelas.store')}}" method="POST">
                                @endisset
                                @csrf
                                <div class="form-group">
                                    <label>Nama</label>
                                    <input type="text" name="nama" placeholder="Masukan Nama Kelas" class="form-control"
                                        value="{{old('nama', $kelas->nama ?? '')}}" required>
                                </div>
                                <div class="form-group">
                                    <label>Ruang</label>
                                    <input type="number" name="nomor" placeholder="Masukan Nomor Kelas" class="form-control"
                                        value="{{old('nomor', $kelas->nomor ?? '')}}" required>
                                </div>
                                <div class="form-group">
                                    <label>Walikelas</label>
                                    <select name="guru_id" class="custom-select">
                                        @isset($kelas)
                                        @foreach ($guru as $item)
                                        <option value={{$item->id}} @if($item->id==$kelas->guru_id)
                                            selected @endif>{{$item->nama}}</option>
                                        @endforeach
                                        @else
                                        <option value='' selected disabled>--Pilih--</option>
                                        @foreach ($guru  as $item)
                                        <option value={{$item->id}}>{{$item->nama}}</option>
                                        @endforeach
                                        @endisset
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Jurusan</label>
                                    <select name="jurusan_id" class="custom-select">
                                        @isset($kelas)
                                        @foreach ($jurusan as $item)
                                        <option value={{$item->id}} @if($item->id==$kelas->prodi_id)
                                            selected @endif>{{$item->nama}}</option>
                                        @endforeach
                                        @else
                                        <option value='' selected disabled>--Pilih--</option>
                                        @foreach ($jurusan  as $item)
                                        <option value={{$item->id}}>{{$item->nama}}</option>
                                        @endforeach
                                        @endisset
                                    </select>
                                </div>
                                <br>
                                <div class="form-group">
                                    <input type="submit" value="Simpan" class="btn btn-primary">
                                    <a href="{{URL::previous()}}" class="btn btn-danger">Batal</a>
                                </div>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/kelas/index.blade.php
@extends('admin.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Kelas </li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">Kelas </h1>
        </header>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 style="float:left"></h4>
                        <div style="float:right">
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a href="{{route('kelas.create')}}" class="btn btn-primary btn-sm">Tambah</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table" id="table">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama</th>
                                        <th>Ruang</th>
                                        <th>Jurusan</th>
                                        <th>Walikelas</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('custom-script')
<script type="text/javascript">
    $(document).ready(function() {
        $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
        });

        var table = $('#table').DataTable({
            processing: true,
            serverSide: true,
            ajax:"{{ route('kelas.index') }}",
            columns:[
            {data: 'DT_RowIndex', name: 'DT_RowIndex', searchable:false, orderable:false},
            {data: 'nama', name: 'nama'},
            {data: 'nomor', name: 'nomor'},
            {data: 'jurusan', name: 'jurusan'},
            {data: 'walikelas', name: 'walikelas'},
            {data: 'action', name: 'action', searchable:false, orderable:false},
            ]
        });

        $('body').on('click', '.deleteProduct', function () {
            var data_id = $(this).data("id");
            confirm("Apakah anda yakin untuk menghapus!");
            var url = '{{ route("kelas.destroy", ":id") }}';
            url = url.replace(':id', data_id );
            $.ajax({
                type: "DELETE",
                url: url,

                success: function (data) {
                    table.draw();
                },
                error: function (data) {
                    console.log('Error:', data);
                }
            });
        });
    })
</script>
@endsection

resources/views/admin/kelas/index_walikelas.blade.php
@extends('admin.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{url('/')}}">Home</a></li>
            <li class="breadcrumb-item active">Nilai Akademik</li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">List Walikelas </h1>
        </header>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table" id="kelas-table">
                                <thead>
                                    <tr>
                                        <th>Kelas</th>
                                        <th>Jurusan</th>
                                        <th>Nomor</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('custom-script')
<script>
    $(document).ready(function() {
        $('#kelas-table').DataTable({
            processing: true,
            serverSide: true,
            ajax:"{{ route('aaaa') }}",
            columns:[
            {data: 'nama', name: 'nama'},
            {data: 'jurusan', name: 'jurusan'},
            {data: 'nomor', name: 'nomor'},
            {data: 'action', name: 'action', searchable:false, orderable:false},
            ]
        });
    })
</script>
@endsection