routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('tes','HomeController@query');
Auth::routes();

Route::group(['prefix' => 'siswa'], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/raport','HomeController@indexRaport')->name('index.raport.siswa');
    Route::get('/cetak-raport/{id}','HomeController@printRaport')->name('print.raport.siswa');
    Route::get('/akun/{id}','SiswaController@akun')->name('akun.siswa.show');
    Route::post('/akun/ubah/{id}','SiswaController@updateAkun')->name('akun.siswa.update');
});

Route::get('raport', 'RaportController@cetak');
Route::get('/','GuruController@index')->middleware('guru');

Route::group(['middleware'=>'guru', 'prefix' => 'admin'], function () {
    Route::get('/','GuruController@index');
    Route::resource('guru', 'GuruController');
    Route::resource('siswa', 'SiswaController');
    Route::resource('jurusan', 'JurusanController');
    Route::resource('matapelajaran', 'MatapelajaranController');
    Route::resource('kelas', 'KelasController');
    Route::resource('nilai-akademik', 'NilaiakademikController')->except('create');
    Route::resource('raport', 'RaportController')->except('create');
    Route::resource('ekskul', 'EkskulController');
    Route::resource('pkl', 'PKLController');
    Route::get('/akun/{id}','GuruController@akun')->name('akun.guru.show');
    Route::post('/akun/ubah/{id}','GuruController@updateAkun')->name('akun.guru.update');

    Route::get('raport/create/{id}', 'RaportController@create')->name('raport.create');
    Route::get('raport/kelas/{kelas}/nilai-akademik', 'RaportController@indexNilai')->name('raport.index.nilai');
    Route::get('raport/kelas/{kelas}/nilai-akademik/tambah', 'RaportController@createNilai')->name('raport.create.nilai');
    Route::get('raport/kelas/{kelas}/nilai-akademik/buat', 'RaportController@generateNilai')->name('raport.generate.nilai');
    Route::post('raport/kelas/{id}/nilai-akademik/cek', 'RaportController@checkNilai')->name('raport.check.nilai');
    Route::post('raport/kelas/{id}/nilai-akademik/generate', 'RaportController@generateNilai')->name('raport.generate.nilai');
    Route::post('raport/kelas/{kelas}/nilai-akademik/detail', 'RaportController@detailNilai')->name('raport.detail.nilai');

    Route::get('nilai-akademik/siswa/{id}', 'NilaiakademikController@indexNilai')->name('cari.nilai.siswa');
    Route::get('nilai-akademik/kelas/{kelas}/mapel/', 'NilaiakademikController@indexMapel')->name('nilai.mapel.index');
    Route::get('nilai-akademik/kelas/{kelas}/mapel/{mapel}', 'NilaiakademikController@indexNilai')->name('nilai.index2');
    Route::post('nilai-akademik/kelas/{kelas}/mapel/{mapel}/tambah', 'NilaiakademikController@create')->name('nilai-akademik.create');
    Route::get('raport/siswa/{id}', 'RaportController@indexNilai')->name('cari.raport.siswa');
    Route::get('nilai-akademik/create/{id}', 'NilaiakademikController@create')->name('nilai.siswa.create');
    Route::post('nilai-akademik/find-semester', 'NilaiakademikController@orderBySemester')->name('nilai.siswa.semester');
    Route::post('nilai-akademik/find-semester-edit/{id}', 'NilaiakademikController@orderBySemesterEdit')->name('nilai.siswa.semester2');

    Route::get('kepsek','HomeController@kepsekForm')->name('kepsek.show');
    Route::post('kepsek/update','HomeController@kepsekUpdate')->name('kepsek.update');
});

app/Raport.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Raport extends Model
{
    protected $table = 'raport';
    protected $fillable = [
        'nilaiakademik_id',
        'pkl_siswa_id',
        'ekskul_siswa_id',
        'cat_akademik',
        'peringkat',
        'sakit',
        'izin',
        'tanpa_ket',
        'keterangan_kenaikan',
        'guru_id',
    ];

    public function nilaiAkademik()
    {
        return $this->belongsTo('App\Nilaiakademik','nilaiakademik_id');
    }

    public function PKLSiswa()
    {
        return $this->belongsTo('App\PKLSiswa','pkl_siswa_id');
    }

    public function ekskulSiswa()
    {
        return $this->belongsTo('App\EkskulSiswa','ekskul_siswa_id');
    }

    public function guru()
    {
        return $this->belongsTo('App\Guru','guru_id');
    }
}

app/Http/Controllers/RaportController.php
<?php

namespace App\Http\Controllers;

use App\Ekskul;
use App\EkskulSiswa;
use App\Kelas;
use App\Kepsek;
use App\Matapelajaran;
use App\Nilaiakademik;
use App\PKL;
use App\PKLSiswa;
use App\Raport;
use App\Siswa;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class RaportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() //fungsi untuk menampilkan data kelas
    {
        if(request()->ajax()){
            $data = Kelas::with('guru')->with('jurusan')->where('guru_id','=',Auth::user()->guru->id)->get();
            //data kelas yang ditampilkan berdasarkan akun guru yang terdaftar sebagai walikelas
            return datatables()->of($data)
                    ->addIndexColumn()
                    ->addColumn('jurusan', function($data){
                        return empty($data->jurusan->nama) ? "Belum Diatur" : $data->jurusan->nama;
                    })
                    ->addColumn('walikelas', function($data){
                        return empty($data->guru->nama) ? "Belum Diatur" : $data->guru->nama;
                    })
                    ->addColumn('action', function($data){
                        $button = '<div class="btn-group" role="group" aria-label="Basic example">
                        <a href="'.route("raport.index.nilai",$data->id).'"class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                        </div>';
                        return $button;
                    })
                    ->rawColumns(['action','walikelas','jurusan'])
                    ->make(true);
        }
        return view('admin.raport.index_kelas');
    }

    public function indexNilai($kelas) //fungsi untuk menampikan nilai akademik yang sudah dibuat walikelas dan dikategorikan berdasarkan angkatan, tahun ajaran dan semester
    {
        $kelas = Kelas::findOrFail($kelas); //mendapatkan nilai siswa berdasarkan kelas yang dipilih saat halaman utama raport
        $nilaiakademik = Nilaiakademik::where('nama_kelas','=',$kelas->nama)
        ->where('nama_jurusan','=',$kelas->jurusan->nama)
        ->where('nomor_kelas','=',$kelas->nomor)
        ->get()->groupBy(['angkatan','tahun','semester']); //mendaparkan data nilai akademik siswa yang dikategorikan berdasarkan angaktan,tahun dan semester

        return view('admin.raport.index_nilai',compact('kelas','nilaiakademik')); //mengarahkan ke halaman pertama menu raport
    }

    public function detailNilai(Request $request,$kelas) //fungsi untuk menampilkan siswa beserta nilai akademiknya
    {
        $kelas = Kelas::findOrFail($kelas); //mendapatkan nilai siswa berdasarkan kelas yang dipilih saat halaman utama raport
        $nilaiakademik = Nilaiakademik::with('siswa')
        ->where('nama_kelas','=',$kelas->nama)
        ->where('nama_jurusan','=',$kelas->jurusan->nama)
        ->where('nomor_kelas','=',$kelas->nomor)
        ->where('semester','=',$request->semester)
        ->where('tahun','=',$request->tahun)
        ->where('angkatan','=',$request->angkatan)->get(); //menampilkan data nilai akademik siswa setelah tadi kita pilih nilai akademik yang dikategorikan
        $tahun = $request->tahun;
        return view('admin.raport.index3',compact('nilaiakademik','kelas','tahun')); //mengarahkan ke halaman yang menampilkan data siswa beserta nilai akademiknya
    }

    public function createNilai($kelas) //menyiapkan form untuk halaman buat nilai akademik yang akan di proses walikelas
    {
        $kelas = Kelas::findOrFail($kelas); //mendapatkan data kelas berdasarkan data yang dipilih di halaman utama menu raport
        return view('admin.raport.create_nilai',compact('kelas')); //mengarahkan ke halaman untuk buat nilai akademik
    }

    public function checkNilai(Request $request, $id) //fugnsi menampilkan list siswa pada halaman buat nilai akademik
    {
        $kelas = Kelas::findOrFail($id); //mendapatkan data kelas berdasarkan data yang dipilih di halaman utama menu raport
        $siswa = Siswa::where('angkatan_thn','=',$request->angkatan)->where('kelas_id','=',$id)->get(); //mendapatkan data seluruh siswa berdasarkan tahun angkatan
        $angkatan = $request->angkatan;
        return view('admin.raport.create_nilai',compact('kelas','siswa','angkatan')); //mengarahkan kembali ke halaman tambah/buat nilai akademik
    }

    public function generateNilai(Request $request, $kelas) //fungsi untuk membuat nilai akademik siswa oleh walikelas yang nantinya akan digunakan guru untuk input nilai akademik
    {
        $siswa = Siswa::where('angkatan_thn','=',$request->angkatan)->where('kelas_id','=',$kelas)->get(); //mendapatka data siswa berdasarkan angkatan dan kelas
        $matapelajaran = Matapelajaran::where('semester','=',$request->semester)->get(); //mendapatkan data matapelajaran berdasarkan semester yang telah diinput di halaman tambah nilai akademik
        if (!$matapelajaran->first()) { //jika matapelajaran pada semester yang dipilih kosong maka proses tidak bisa dilanjut
            return redirect()->to('admin/raport/kelas/'.$kelas.'/nilai-akademik/tambah')->withErrors('data matapelajaran pada semester '.$request->semester.' kosong');
        }
        foreach ($siswa as $value) { //proses pembuatan nilai akademik untuk seluruh siswa berdasarkan kelas
            Nilaiakademik::create([
                'siswa_id'=>$value->id,
                'tahun'=>$request->tahun,
                'semester'=>$request->semester,
                'nama_kelas'=>$value->kelas->nama,
                'nama_jurusan'=>$value->kelas->jurusan->nama,
                'nomor_kelas'=>$value->kelas->nomor,
                'angkatan'=>$value->angkatan_thn,
                ]);
        }

        return redirect()->route("raport.index.nilai",$kelas)->with(['success'=>'Berhasil menambah data, guru dapat input nilai siswa']); //mengarahkan ke halaman pilih nilai akademik di menu raport
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id) //fungsi untuk menyiapkan formulir pembuatan raport
    {
        $record = Nilaiakademik::with('siswa')->find($id); //mendapatkan data nilai akademik berdsarkan nilai akademik yang dipilih
        $matapelajaran = Matapelajaran::where('semester','=',$record->semester)->get(); //mendapatkan data matapelajaran untuk halaman buat raport
        $pkl = PKL::all(); //mendapatkan data pkl
        $ekskul = Ekskul::all(); //mendapatkan data eksul
        $kenaikan = ['Naik','Tidak Naik']; //pilihan untuk status kenaikan kelas siswa
        $kelas = Kelas::all(); //mendapatkan data kelas

        return view('admin.raport.create',compact('record','matapelajaran','pkl','ekskul','kenaikan','kelas')); //mengarahkan ke halaman pembuatan raport
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) //fungsi penyimpanan data raport yang telah diisi di halaman pembuatan raport
    {
        $nilaiakademik = Nilaiakademik::with('siswa')->find($request->nilaiakademik_id); //mendapatkan data nilai akademik dari database
        $matapelajaran = Matapelajaran::where('semester','=',$nilaiakademik->semester)->get(); //mendapatkan data mata pelajaran dari database berdasarkan semester
        $list_pkl = PKL::all(); //mendapatkan data pkl dari database
        $list_ekskul = Ekskul::all(); //mendapatkan data ekskul dari database

        $raport = Raport::create([
            'nilaiakademik_id' => $nilaiakademik->id,
            'cat_akademik' => $request->cat_akademik,
            'sakit' => $request->sakit,
            'izin' => $request->izin,
            'tanpa_ket' => $request->tanpa_ket,
            'keterangan_kenaikan'=>$request->keterangan_kenaikan,
            'guru_id'=>Auth::user()->guru->id,
        ]); //proses penyimpanan data raport ke database

        /*
            proses penyimpanan data pkl dan ekskul persiswa ini agak ribet karena
            relasi tabelnya many to many jadi diperlukan tabel pivot yang namanya
            tabel nilai akademik + tabel pkl_siswa = pivot tabel hasil_pkl_siswa
            tabel nilai akademik + tabel ekskul_siswa = pivot tabel hasil_pkl_siswa
        */
        if ($request->pkl) { //proses penyimpanan data pkl jika diisi
            $pkl = PKLSiswa::create([
                'tahun'=>$nilaiakademik->tahun,
                'semester'=>$nilaiakademik->semester,
                'siswa_id'=>$nilaiakademik->siswa_id,
            ]); //proses simpan data pkl siswa jika ada pilih pkl saat buat raport
            for ($i=1; $i <= count($request->pkl) ; $i++) {
                foreach ($list_pkl as $value) {
                    if ($value->id == $request->pkl[$i]) {
                        $pkl_id_array[$value->id] = [
                            'lamanya' => $request->lamanya[$i],
                            'keterangan' => $request->keterangan[$i],
                        ];
                    }
                }
            }
            $pkl->hasilPKL()->attach($pkl_id_array);
            $raport->pkl_siswa_id = $pkl->id;
            //intinya ini proses penambahan data pkl siswa dan proses sinkronsasi data pkl ke nilai akademik untuk raport
        }

        if ($request->ekskul) { //sama aja kayak diatas cuman ini untuk data ekskul
            $ekskul = EkskulSiswa::create([
                'tahun'=>$nilaiakademik->tahun,
                'semester'=>$nilaiakademik->semester,
                'siswa_id'=>$nilaiakademik->siswa_id,
            ]);
            for ($i=1; $i <= count($request->ekskul) ; $i++) {
                foreach ($list_ekskul as $value) {
                    if ($value->id == $request->ekskul[$i]) {
                        $ekskul_id_array[$value->id] = [

resources/views/admin/raport/create.blade.php
@extends('admin.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Raport </li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">Raport </h1>
        </header>
        <div class="card">
            <div class="card-body">
                <div class="media align-items-center">
                    <div class="media-body overflow-hidden">
                        <h5 class="card-text mb-0">{{$record->siswa->nama}}</h5>
                        <p class="card-text text-uppercase">Kelas {{$record->siswa->kelas->nama ?? ''}}</p>
                        <p class="card-text">NIS: {{$record->siswa->nis ?? "belum diatur"}}<br></p>
                    </div>
                </div><a href="#" class="tile-link"></a>
            </div>
        </div>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                <li>Proses Gagal!!!</li>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header d-flex align-items-center">
                        <h4>Nilai Akademik</h4>
                    </div>
                        <div class="card-body">
                            <div class="form-group">
                                <label>Semester : {{$record->semester}}</label>
                            </div>
                            <div class="form-group">
                                <label>Tahun : {{$record->tahun}}</label>
                            </div>
                        </div>
                </div>
                <div class="card">
                    <div class="card-header d-flex align-items-center">
                        <h4>Data Raport</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{route('raport.store')}}" method="POST">
                            @csrf
                            @include('admin.raport.form')
                            <input type="hidden" name="nilaiakademik_id" value="{{$record->id}}">
                            <input type="hidden" name="kelas_id" value="{{$record->siswa->kelas->id}}">
                            <div class="form-group">
                                <button type="submit" value="Simpan" class="btn btn-primary">Submit</button>
                                <a href="{{URL::previous()}}" class="btn btn-danger">Batal</a>
                            </div>
                        </form>
                    <div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/raport/create_nilai.blade.php
@extends('admin.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Raport </li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">Nilai Akademik </h1>
        </header>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                <li>Proses Gagal!!!</li>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Cek Siswa Kelas {{$kelas->nama}} {{$kelas->jurusan->nama}} {{$kelas->nomor}}</h4>
            </div>
            <div class="card-body">
                <form action="{{route('raport.check.nilai',$kelas->id)}}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label>Angkatan Tahun</label>
                        <input type="number" name="angkatan" placeholder="Masukan Tahun" class="form-control"
                            value="{{old('angkatan', $angkatan ?? '')}}" required>
                    </div>
                    <br>
                    <div class="form-group">
                        <input type="submit" value="Cek" class="btn btn-primary">
                    </div>
                </form>
            </div>

        </div>
        @isset($angkatan)
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <h4>Tambah Data Nilai Akademik Kelas {{$kelas->nama}} {{$kelas->jurusan->nama}} {{$kelas->nomor}} Angkatan {{$angkatan}}</h4>
            </div>
            <div class="card-body">
                <form action="{{route('raport.generate.nilai',$kelas->id)}}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Semester</label>
                                <input type="number" name="semester" placeholder="Masukan Semester" class="form-control"
                                    value="{{old('semester', $nilai->semester ?? '')}}" required>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Tahun Ajaran</label>
                                <input type="number" name="tahun" placeholder="Masukan Tahun" class="form-control"
                                    value="{{old('tahun', $nilai->tahun ?? '')}}" required>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="angkatan" value="{{$angkatan}}">
                    <br>
                    <div class="table-responsive table-striped">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nis</th>
                                    <th>Nama</th>
                                    <th>Angkatan</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $x=1;?>
                                @foreach ($siswa as $item)
                                <tr>
                                    <td scope="row">{{$x++}}</th>
                                    <td>{{$item->nis}}</td>
                                    <td>{{$item->nama}}</td>
                                    <td>{{$item->angkatan_thn}}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <br>
                    <div class="form-group">
                        <input type="submit" value="Simpan" class="btn btn-primary">
                    </div>
                </form>
            </div>

        </div>
        @endisset
    </div>
</section>
@endsection

resources/views/admin/raport/index3.blade.php
@extends('admin.layout')

@section('custom-style')
    <style>
        .nilai-akademik thead th{
            border: 1px solid grey !important;
            vertical-align: middle;
            text-align: center;
        }
        .nilai-akademik tbody td{
            text-align: center;
        }
    </style>
@endsection

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Nilai Akademik </li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">List Data Nilai Akademik </h1>
        </header>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 style="float:left">
                            {{$kelas->nama}} {{$kelas->jurusan->nama}} {{$kelas->nomor}}
                        </h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive table-striped nilai-akademik">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th class="text-center" rowspan="2">#</th>
                                        <th rowspan="2">Nama</th>
                                        <th rowspan="2">Semester</th>
                                        <th rowspan="2">Tahun</th>
                                        <th class="text-center" colspan="3">Total</th>
                                        <th class="text-center" colspan="4">rata-rata</th>
                                        <th rowspan="2">Aksi</th>
                                    </tr>
                                    <tr>
                                        <th>Pengetahuan</th>
                                        <th>Keterampilan</th>
                                        <th>Nilai Akhir</th>
                                        <th>Pengetahuan</th>
                                        <th>Keterampilan</th>
                                        <th>Nilai Akhir</th>
                                        <th>Predikat</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $x=1;?>
                                    @foreach ($nilaiakademik as $item)
                                    <tr>
                                        <td scope="row">{{$x++}}</th>
                                        <td>{{$item->siswa->nama}}</td>
                                        <td>{{$item->semester}}</td>
                                        <td>{{$item->tahun}}</td>
                                        <td>{{$item->sum_pengetahuan}}</td>
                                        <td>{{$item->sum_keterampilan}}</td>
                                        <td>{{$item->sum_nilai_akhir}}</td>
                                        <td>{{$item->avg_pengetahuan}}</td>
                                        <td>{{$item->avg_keterampilan}}</td>
                                        <td>{{$item->avg_nilai_akhir}}</td>
                                        <td>{{$item->avg_predikat}}</td>
                                        <td>
                                            <form class="btn-group" role="group" aria-label="Basic example" action="{{ route('nilai-akademik.destroy',$item->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                @if ($item->raport)
                                                <a href="{{route('raport.edit',$item->id)}}"
                                                    class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                                                <a href="{{route('raport.show',$item->id)}}"
                                                    class="btn btn-primary btn-sm"><i class="fa fa-eye"></i></a>
                                                @else
                                                <a href="{{route('raport.create',$item->id)}}"
                                                    class="btn btn-info btn-sm"><i class="fa fa-plus"></i></a>
                                                @endif
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/raport/index_kelas.blade.php
@extends('admin.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{url('/')}}">Home</a></li>
            <li class="breadcrumb-item active">Raport</li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">List Kelas </h1>
        </header>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">

                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table" id="student-table">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama</th>
                                        <th>Jurusan</th>
                                        <th>Nomor</th>
                                        <th>Walikelas</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('custom-script')
<script>
    $(document).ready(function() {
        $('#student-table').DataTable({
            processing: true,
            serverSide: true,
            ajax:"{{ route('raport.index') }}",
            columns:[

            {data: 'DT_RowIndex', name: 'DT_RowIndex', searchable:false, orderable:false},
            {data: 'nama', name: 'nama'},
            {data: 'jurusan', name: 'jurusan'},
            {data: 'nomor', name: 'nomor'},
            {data: 'walikelas', name: 'walikelas'},
            {data: 'action', name: 'action', searchable:false, orderable:false},
            ]
        });
    })
</script>
@endsection